### PR TITLE
[AETHER-3550] Regenerating gNMI clients with ordered endpoints

### PR DESCRIPTION
**Pull request by teone**
And reactivating the test to make sure the generated code matches the committed code

### CODE REVIEW

**Comment by teone** [comment]
retest this please

**Review by SeanCondon — APPROVED** [review]
impossible to make a comparison on these Go changes, but that's the whole idea - they will be consistent from here on

**Comment by SeanCondon** [comment]
@teone can this be closed now?

**Comment by teone** [comment]
@SeanCondon yes I think it's ok to close, the models have probably been regenerated a few times since then

**Pull request closed without merging**
